export const CONTRACT_ID = "dev-1668567287519-97631944136604";

export const JOBS_CATEGORIES = [
  "web | html | info design",
  "business | mgmt",
  "marketing | advertising | pr",
  "et cetera",
  "writing | editing",
  "software | qa | dba | etc",
  "accounting | finance",
  "admin | office",
  "art | media | design",
  "healthcare",
  "retail | wholesale",
  "nonprofit",
  "legal | paralegal",
  "architect | engineer | cad",
  "sales",
  "systems | networking",
  "tv | film | video | radio",
  "human resource",
  "technical support",
  "education | teaching",
  "skilled trades | artisan",
  "government",
  "science | biotech",
  "customer service",
  "transportation",
  "salon | spa | fitness",
  "real estate",
  "manufacturing",
  "food | beverage | hospitality",
  "general labor",
  "security",
];

export const HOUSING_CATEGORIES = [
  "apartments | housing for rent",
  "wanted: apts",
  "rooms & shares",
  "wanted: room | share",
  "sublets & temporary",
  "office & commercial",
  "parking & storage",
  "wanted: sublet | temp",
  "housing swap",
  "vacation rentals",
  "wanted: real estate",
  "real estate - by owner",
];

export const COMMUNITY_CATEGORIES = [
  "general",
  "volunteers",
  "activity partners",
  "rideshare",
  "pets",
  "childcare",
  "missed connections",
  "artists",
  "musicians",
  "politics",
  "lost & found",
  "rants & raves",
  "groups",
  "local news and views",
];

export const FOR_SALE_CATEGORIES = [
  "general for sale",
  "computers",
  "wanted",
  "barter",
  "tickets",
  "bicycles",
  "motorcycles | scooters",
  "garage & moving sales",
  "books & magazines",
  "sporting goods",
  "clothing & accessories",
  "collectibles",
  "electronics",
  "household items",
  "musical instruments",
  "free stuff",
  "baby & kid stuff",
  "cds | dvds | vhs",
  "tools",
  "boats",
  "jewelry",
  "auto parts",
  "rvs",
  "toys & games",
  "farm & garden",
  "business | commercial",
  "arts & crafts",
  "materials",
  "photo | video",
  "furniture",
  "cars & trucks",
  "appliances",
  "antiques",
  "video gaming",
  "health and beauty",
  "cell phones",
  "atvs | utvs | snowmobiles",
  "heavy equipment",
  "motorcycle parts",
  "bicycle parts",
  "computer parts",
  "boat parts",
  "auto wheels & tires",
  "trailers",
  "aviation",
];

export const POSTINGTYPES = [
  "Job Offered",
  "Housing Wanted",
  "Housing Offered",
  "For Sale by Owner",
  "For Sale by Dealer",
  "Wanted by Owner",
  "Wanted by Dealer",
  "Community",
];

export const CONDITIONITEMS = [
  "New",
  "LikeNew",
  "Excellent",
  "Good",
  "Fair",
  "Salvage",
];

export const COMMUNITYITEMS = [
  "Garage Sale",
  "Class or Event",
  "Lost or Found",
  "RideShare",
];

export const EMPLOYMENTITEMS = [
  "FullTime",
  "PartTime",
  "ContractWork",
  "EmployeeChoice",
];

export const HOUSINGTYPEITEMS = [
  "Apartment",
  "Condo",
  "CottageOrCabin",
  "Duplex",
  "Flat",
  "House",
  "InLaw",
  "Loft",
  "TownHouse",
  "Manufactured",
  "AssistedLiving",
  "Land",
];

export const HOUSINGPERTIMEITEMS = ["Day", "Week", "Month"];


export const THEMES = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
];